# Generated by Django 3.0.8 on 2020-08-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishTitle', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(default='2020-08-10')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Course')),
            ],
            options={
                'ordering': ['dishTitle'],
            },
        ),
    ]
