# Generated by Django 3.0.8 on 2020-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['dish_title']},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='dishTitle',
            new_name='dish_title',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='output_price',
            field=models.FloatField(default=0),
        ),
    ]
