# Generated by Django 3.0.8 on 2020-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200810_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='output_price',
            field=models.CharField(max_length=250),
        ),
    ]
