# Generated by Django 3.0.8 on 2020-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200810_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='output_price',
            field=models.FloatField(default=0),
        ),
    ]
