# Generated by Django 3.0.8 on 2020-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200810_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='output_price',
            field=models.CharField(max_length=250),
        ),
    ]
