# Generated by Django 3.0.8 on 2020-07-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200720_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='course',
        ),
    ]
